name: Vulnerabilidade
description: Triage de vulnerabilidade (CVSS, impacto, plano)
labels: [security, triage]
body:
  - type: input
    id: source
    attributes: { label: Fonte (SAST/DAST/SCA/GH Alerts) }
  - type: dropdown
    id: severity
    attributes:
      label: Severidade (CVSS)
      options: [Critical (>=9), High (7-8.9), Medium (4-6.9), Low (<4)]
  - type: textarea
    id: context
    attributes: { label: Contexto/Impacto }
  - type: textarea
    id: fix
    attributes: { label: Mitigação/Correção proposta }
  - type: input
    id: sla
    attributes: { label: SLA (data limite) }
